@echo off
mkdir "public\beats" 2>nul

ffmpeg -y -i "beats\Base Gueto - Beat Tipo Racionais Mc's - Instrumental ( Uso Livre ) [EHU20fbJyOk].mp3" -c:a libopus -b:a 96k "public\beats\basegueto-beattiporacionaismcs-instrumentalusolivreehu20fbjyok.opus"
ffmpeg -y -i "beats\Capítulo 4, Versículo 3 - Instrumental em Vinil [7v9HuNKBSaY].mp3" -c:a libopus -b:a 96k "public\beats\captulo4versculo3-instrumentalemvinil7v9hunkbsay.opus"
ffmpeg -y -i "beats\Chama os Mulekes [ INSTRUMENTAL ] - CONE CREW DIRETORIA - [ OFICIAL ] - [ ÁUDIO ] - [ FULL HD ] - Rap Cone Crew Diretoria (youtube).mp3" -c:a libopus -b:a 96k "public\beats\chamaosmulekesinstrumental-conecrewdiretoria-oficial-udio-fullhd-rapconecrewdiretoriayoutube.opus"
ffmpeg -y -i "beats\Crime Vai e Vem - Instrumental em Vinil [1jG6KUEhstE].mp3" -c:a libopus -b:a 96k "public\beats\crimevaievem-instrumentalemvinil1jg6kuehste.opus"
ffmpeg -y -i "beats\Diário de um Detento - Instrumental em Vinil [w-hNt5rgZ4k].mp3" -c:a libopus -b:a 96k "public\beats\diriodeumdetento-instrumentalemvinilw-hnt5rgz4k.opus"
ffmpeg -y -i "beats\Expresso da Meia Noite - Instrumental em Vinil [qr99texOjx4].mp3" -c:a libopus -b:a 96k "public\beats\expressodameianoite-instrumentalemvinilqr99texojx4.opus"
ffmpeg -y -i "beats\Fórmula Mágica da Paz - Instrumental em Vinil [iEZK28Qd8nU].mp3" -c:a libopus -b:a 96k "public\beats\frmulamgicadapaz-instrumentalemviniliezk28qd8nu.opus"
ffmpeg -y -i "beats\Gangsta's Paradise (Instrumental) - 916ej (youtube).mp3" -c:a libopus -b:a 96k "public\beats\gangstasparadiseinstrumental-916ejyoutube.opus"
ffmpeg -y -i "beats\Instrumental ⧸ Beat - Racionais - Preto Zica [U_r7MrWHRoU].mp3" -c:a libopus -b:a 96k "public\beats\instrumentalbeat-racionais-pretozicaur7mrwhrou.opus"
ffmpeg -y -i "beats\INSTRUMENTAL ｜ Marighella (Mil Faces De Um Homem Leal) - Racionais [9szPl6IKoBM].mp3" -c:a libopus -b:a 96k "public\beats\instrumentalmarighellamilfacesdeumhomemleal-racionais9szpl6ikobm.opus"
ffmpeg -y -i "beats\O Homem na Estrada - Instrumental em Vinil [XPmGb3PQ6Yw].mp3" -c:a libopus -b:a 96k "public\beats\ohomemnaestrada-instrumentalemvinilxpmgb3pq6yw.opus"
ffmpeg -y -i "beats\racionais mc's jorge de capadocia instrumental [zj7jkhv-q_s].mp3" -c:a libopus -b:a 96k "public\beats\racionaismcsjorgedecapadociainstrumentalzj7jkhv-qs.opus"
ffmpeg -y -i "beats\Racionais mcs vida loka parte 1 instrumental [hHc2BGwayQs].mp3" -c:a libopus -b:a 96k "public\beats\racionaismcsvidalokaparte1instrumentalhhc2bgwayqs.opus"
ffmpeg -y -i "beats\Racionais mcs vida loka parte 2 instrumental [qv7FOKsQ6EE].mp3" -c:a libopus -b:a 96k "public\beats\racionaismcsvidalokaparte2instrumentalqv7foksq6ee.opus"
ffmpeg -y -i "beats\Racionais Mcs- ＂A Vítima＂(instrumental) [6YZgH48gBHk].mp3" -c:a libopus -b:a 96k "public\beats\racionaismcs-avtimainstrumental6yzgh48gbhk.opus"
ffmpeg -y -i "beats\The Passion HiFi - Bittersweet.mp3" -c:a libopus -b:a 96k "public\beats\thepassionhifi-bittersweet.opus"
ffmpeg -y -i "beats\The Passion HiFi - Buried.mp3" -c:a libopus -b:a 96k "public\beats\thepassionhifi-buried.opus"
ffmpeg -y -i "beats\The Passion HiFi - Cold Heat.wav" -c:a libopus -b:a 96k "public\beats\thepassionhifi-coldheat.opus"
ffmpeg -y -i "beats\the passion hifi - cynical plans.mp3" -c:a libopus -b:a 96k "public\beats\thepassionhifi-cynicalplans.opus"
ffmpeg -y -i "beats\The Passion HiFi - I Love U Baby.wav" -c:a libopus -b:a 96k "public\beats\thepassionhifi-iloveubaby.opus"
ffmpeg -y -i "beats\The Passion HiFi - Lab Classic.mp3" -c:a libopus -b:a 96k "public\beats\thepassionhifi-labclassic.opus"
ffmpeg -y -i "beats\The Passion HiFi - Laws of Movement.wav" -c:a libopus -b:a 96k "public\beats\thepassionhifi-lawsofmovement.opus"
ffmpeg -y -i "beats\The Passion HiFi - Let The Bass Kick.mp3" -c:a libopus -b:a 96k "public\beats\thepassionhifi-letthebasskick.opus"
ffmpeg -y -i "beats\The Passion HiFi - Like a Ho.mp3" -c:a libopus -b:a 96k "public\beats\thepassionhifi-likeaho.opus"
ffmpeg -y -i "beats\The Passion Hifi - Mo' Blues.mp3" -c:a libopus -b:a 96k "public\beats\thepassionhifi-moblues.opus"
ffmpeg -y -i "beats\The Passion HiFi - My Obstacles.mp3" -c:a libopus -b:a 96k "public\beats\thepassionhifi-myobstacles.opus"
ffmpeg -y -i "beats\The Passion HiFi - NARC.wav" -c:a libopus -b:a 96k "public\beats\thepassionhifi-narc.opus"
ffmpeg -y -i "beats\The Passion HiFi - Sense and Technique.mp3" -c:a libopus -b:a 96k "public\beats\thepassionhifi-senseandtechnique.opus"
ffmpeg -y -i "beats\The Passion HiFi - The Art of Soul.mp3" -c:a libopus -b:a 96k "public\beats\thepassionhifi-theartofsoul.opus"
ffmpeg -y -i "beats\The Passion HiFi - untouchable.mp3" -c:a libopus -b:a 96k "public\beats\thepassionhifi-untouchable.opus"
ffmpeg -y -i "beats\[FREE] Coolio X UK Drill Type Beat - GANGSTER'S PARADISE  UK Drill Instrumental 2022 - Kezii (youtube).mp3" -c:a libopus -b:a 96k "public\beats\freecoolioxukdrilltypebeat-gangstersparadiseukdrillinstrumental2022-keziiyoutube.opus"
ffmpeg -y -i "beats\[FREE] Piano Type Beat - Gangsta's Paradise  Free Type Beat - D0 Production (youtube).mp3" -c:a libopus -b:a 96k "public\beats\freepianotypebeat-gangstasparadisefreetypebeat-d0productionyoutube.opus"

echo.
echo ===== CONVERSAO CONCLUIDA =====
dir "public\beats"
